# Generated by Django 3.0.10 on 2021-07-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=15)),
                ('slug', models.SlugField(max_length=15, unique=True)),
                ('main_image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Mainimages',
            },
        ),
    ]
